name: codephile
description: Codephile.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  firebase_core: ^1.11.0
  firebase_crashlytics: ^2.4.5
  firebase_messaging: ^11.2.5
  firebase_remote_config: ^1.0.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  freezed_annotation: ^1.1.0
  get: ^4.6.1
  hive_flutter: ^1.1.0
  hydrated_bloc: ^8.0.0
  json_annotation: ^4.4.0
  sentry_flutter: ^6.2.2

dev_dependencies:
  build_runner: ^2.1.7
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  freezed: ^1.1.1
  json_serializable: ^6.1.4

flutter:
  uses-material-design: true
