name: codephile
description: Codephile.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cached_network_image: ^3.2.0
  card_swiper: ^2.0.1
  dio: ^4.0.4
  dropdown_search: ^2.0.1
  equatable: ^2.0.3
  firebase_core: ^1.11.0
  firebase_crashlytics: ^2.4.5
  firebase_messaging: ^11.2.5
  firebase_remote_config: ^1.0.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_screenutil: 5.0.4
  flutter_svg: ^1.0.3
  flutter_typeahead: ^3.2.4
  flutter_web_browser: ^0.17.0
  freezed_annotation: ^1.1.0
  get: ^4.6.1
  hive_flutter: ^1.1.0
  hydrated_bloc: ^8.0.0
  image_cropper: ^1.5.0
  image_picker: ^0.8.4+10
  intl: ^0.17.0
  json_annotation: ^4.4.0
  rxdart: ^0.27.3
  sentry_flutter: ^6.2.2

dev_dependencies:
  bloc_test: ^9.0.2
  build_runner: ^2.1.7
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  freezed: ^1.1.0
  json_serializable: ^6.1.4
  mocktail:

flutter:
  uses-material-design: true
  assets:
    - assets/app/icons/
    - assets/app/images/
    - assets/app/images/platforms/
    - assets/app/illustrations/
